name: Daily Supabase Ping

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 00:00 UTC
  workflow_dispatch:

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Edge Function
        run: |
          curl -X GET "${{ secrets.SUPABASE_EDGE_FUNCTION_URL }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
